### ISSUE TITLE
Issues with linux example: sys/features.h

### ISSUE THREAD

**Issue by ashubhatt** [arrow-acs/acn-embedded#8]
Hey Dev,

I am facing an issue while compiling the linux example. It throws an error because of header file which is not present in my machine. I am using Ubuntu 16.04 with dependencies installed such as build-essentials and libsensors4-dev.

> acn-embedded/acn-sdk-c/include/sys/mem.h:28:27: fatal error: sys/features.h: No such file or directory

The error occurs because of **debug.c**. 
Could you help with the issue?

**Comment by DanilaDemidov** [comment]
Hi,
I have checked and fixed this issue. Please try it again.

**Comment by ashubhatt** [comment]
The issue still persists.. Probably you need to update the git reference of acn-sdk-c in this repo.

Update:
Tried the build after cloning the master branch of acn-sdk-c.
Now the build fails with error:
> acn-embedded/acn-sdk-c/include/sys/mem.h:34:27: fatal error: sys/arch/mem.h: No such file or directory

**Comment by dandemidow** [comment]
I think you just update the submodule. Ok, I have fixed all reference I believe.

About your update
This error could be if the ARCH_MEM was defined. It's means you want handle all memory functions by yourself and should create sys/arch/mem.h file. I think that for a linux machine it is not necessary. Don't add this define.
