### ISSUE TITLE
Firmware Update Example for Quadro

### ISSUE THREAD

**Issue by CoryArrow** [arrow-acs/acn-embedded#9]
Hello,

Is there any chance of getting an example of how to implement firmware updates for the Quadro board (../acnsdkc/arrow/update.c) as seen with other platforms?

**Comment by CoryArrow** [comment]
Additionally, would it be possible to give the SDK the ability to query Arrow Connect for the URL to the file to download? This would allow the pre-existing OTA library in the WICED SDK (or any other SDK's) to manage the file download and perform the update.

Perhaps this could be done by adding a download init callback to the `arrow_software_release_dowload_set_cb` funtion so that the function could be implemented by a user by calling `arrow_software_release_dowload_set_cb(arrow_release_download_init, arrow_release_download_payload, arrow_release_download_complete)` in the main application. If the user were to supply NULL for the download init callback, the SDK could proceed with downloading the image itself, otherwise perform the callback specified the user and allow the main application to take control, i.e. `arrow_software_release_dowload_set_cb(NULL, arrow_release_download_payload, arrow_release_download_complete)` would maintain the current implementation.

I think this would increase the versatility of the SDK and allow us to use to use the built in OTA library in the WICED SDK or any other SDK.

Thoughts?

Thanks!

**Comment by dandemidow** [comment]
Hi,
If you mean direct URL to OTA downloading this capability is still existing. There is arrow_gateway_software_update_set_cb callback for it ( see POST /api/v1/kronos/gateways/{gatewayHid}/actions/software-update ). But I have doubt that this stuff available from firmware update portal but API have it.
There is separate function for init callback (arrow_software_release_init_set_cb) but I want to collect these into one arrow_software_release_dowload_set_cb function in the next release.
I'll try to make it today.
And about the Quadro OTA. There is no this OTA implementation but I can investigate it.

**Comment by CoryArrow** [comment]
I checked the Arrow Connect portal and I haven't found a way to perform a software update, only the software release download. I am inquiring through other channels on how to get this implemented on the cloud portal.

In regards to the init callback, I just pulled your latest changes and found where the callback can be specified but it looks like the update URL is not passed into the callback. Would it be possible to have the URL passed into the specified callback function so that I can kick-off a direct URL to OTA download?

I think if you were to update to init callback to take in the download URL, that should solve the Quadro issue. I am developing an application on a Cypress board based on the CYW943907AEVAL1F and can share my solution with you privately once I have it working and you can implement it into the repo or I can fork and issue a pull request with the required changes.

Thanks!

**Comment by DanilaDemidov** [comment]
Let me clarify this moment. There is software release callbacks for the updating firmware through a portal (Firmware Management system). And there is gateway update API request I wrote above. For handling this request you should use this function
`arrow_gateway_software_update_set_cb(qca_gateway_software_update);`
and set callback (int silex example is **qca_gateway_software_update**)
this callback have only one argument is URL.
You can see in the silex update.c file
```
int qca_gateway_software_update(const char *url) {
  A_UINT32 resp_code,length;
  DBG("url %s", url);
  char *sch_end = strstr((char*)url, "://");
  if ( !sch_end ) return -1;
  if ( strncmp(url, "tftp", 4) == 0 ) {
    DBG("start tftp");
    char *ip_end = strstr((char*)url + 7, "/");
    char *ip = strndup(url+7, (A_UINT32)(ip_end - (char*)url - 7));
    A_UINT32 addr = _inet_addr(ip);
    DBG("ip [%s]", ip);
    free(ip);
    char *filename = ip_end + 1;
    DBG("file [%s]", filename);
    wdt_feed();
    qcom_ota_upgrade(currentDeviceId,
                     addr,
                     filename,
                     0,
                     0,
                     0,
                     &resp_code,
                     &length);

    if ( resp_code != A_OK ) {
      DBG("OTA Download Failed, ERR=%d", resp_code);
      return A_ERROR;
    } else {
      DBG("OTA Download Successful Image Size:%d\n ", length);
    }
    int resp = qcom_ota_done(1);

    if ( resp == 1 ) {
      DBG("OTA Completed Successfully");
      return 0;
    } else {
      DBG("OTA Failed Err:%d  \n", resp);
    }
  ....
etc
```
You can confirm it through a swagger I think.

The init/process/done callbacks are for FWM system only. You get chunks of the OTA file as a https response payload. You don't need any direct link for this.

**Comment by CoryArrow** [comment]
It looks like the only way to get the `qca_gateway_software_update` callback function to trigger is for the system to receive a `ServerToGateway_GatewaySoftwareUpdate` event. So far I have not found a way to get that event to be generated. I have been able to generate `ServerToGateway_DeviceSoftwareRelease` and `ServerToGateway_GatewaySoftwareRelease` events to be generated by trying to schedule firmware updates from the FWM portal, but I have never seen the `ServerToGateway_GatewaySoftwareUpdate` event. Do you know how to get this event to be generated in the SDK?

I have implemented the callback functions with the following:
```
int gateway_software_update_cb(const char *url)
{
    WPRINT_APP_INFO(("Gateway Software Update Callback\r\n"));

    return 0;
}

arrow_gateway_software_update_set_cb(gateway_software_update_cb);
```

I am simply trying to get get the callback handler to print at this point to prove that I am falling into it. How can I get the `ServerToGateway_GatewaySoftwareUpdate` command to my device?

Thanks for your help!

**Comment by DanilaDemidov** [comment]
I can generate it by this script:
```
API_KEY=$1
GATEWAY_HID=$2

curl -X POST \
—header 'Content-Type: application/json' \
—header 'Accept: application/json' \
—header "x-auth-token: $API_KEY" \
-d '{ "url":"http://test.org/ota.bin" }' \
"https://api.arrowconnect.io/api/v1/kronos/gateways/$GATEWAY_HID/actions/software-update"
```
Just change http://test.org/ota.bin in a json payload

**Comment by CoryArrow** [comment]
Is there a way to get the URL where the file is hosted on the Arrow Connect FWM server? Ideally I would prefer to host the image on Arrow Connect only and not have to upload to other locations, additionally the Cypress WiFi boards have a hard time dealing with redirects so I was hoping that getting the Arrow Connect URL to the OTA file would get around this. I understand this may not be possible but just curious if you knew of a way to do this.

Instead of running the script above (which definitely helps me understand the implementation, thanks) I would probably add a command handler to the firmware and just send an "update" command with the image URL as the Payload if there is no way to get the URL from Arrow Connect.

Thanks!

**Comment by DanilaDemidov** [comment]
There is no way to get direct link to an OTA file from the FWM server I think. You should get a token to access this file. And this token you can get only from release update command.
The gateway_software_update_cb should use some external server.

**Comment by CoryArrow** [comment]
That makes sense, I will proceed down the path of implementing the gateway software update method. If you decide to go down the path of creating an OTA example for the Quadro board I would love to see it and leverage it on my board, I'll see what can be done to implement it with the release update mechanism but it's good to know that there is a workaround.

Thanks!
